//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Totales
    {
        public int PK_Totales { get; set; }
        public Nullable<int> PK_Usuarios { get; set; }
        public Nullable<int> PK_Ventas { get; set; }
        public Nullable<int> PK_Producto { get; set; }
    }
}
