//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Modelos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ventas
    {
        public int PK_Ventas { get; set; }
        public Nullable<int> PK_Producto { get; set; }
        public Nullable<int> PK_Usuarios { get; set; }
        public string Producto { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public string Usuario { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Forma_Pago { get; set; }
        public string Total { get; set; }
    
        public virtual Productos Productos { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
